"""
Phase 4 & Production Agent Architecture: Multi-Agent LangGraph Framework
=============================================================================================
Flow: User -> Router Agent -> [RAG | SQL | Web | Math | Python | LLM] -> Planner Agent -> Critic Agent -> Final Response

Optimizations & Features:
  - True Multi-Agent architecture.
  - SQL Agent for querying structured databases.
  - Planner/Synthesizer Agent to draft the response based on worker data.
  - Critic Agent to evaluate the response and enforce self-correction loops.
"""

import os
import sys
import re
import pickle
import sqlite3
import json
from pathlib import Path
from typing import Annotated, List, Sequence, TypedDict, Dict, Any, Optional

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

from pydantic import BaseModel, Field
from langgraph.graph import StateGraph, END, START
from langgraph.graph.message import add_messages

from langchain_core.messages import (
    BaseMessage, HumanMessage, AIMessage, SystemMessage, ToolMessage
)
from langchain_groq import ChatGroq
from langchain_community.tools import DuckDuckGoSearchRun
from langchain_experimental.tools import PythonREPLTool

from hybrid_retriever import HybridRetriever, get_global_cross_encoder
from ingest import get_embedding_model

from dotenv import load_dotenv
load_dotenv()


# ─────────────────────────────────────────────
# STATE DEFINITION
# ─────────────────────────────────────────────

class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], add_messages]
    route: str
    worker_data: str                # Raw data returned by worker agents
    draft_response: str             # Draft generated by the Planner
    critic_feedback: str            # Feedback provided by Critic if rejected
    is_approved: bool               # Critic's approval flag
    critic_retry_count: int         # Track retries to prevent infinite loops
    citations: Optional[List[Dict[str, Any]]]             # For RAG
    groundedness_score: Optional[float]                   # For RAG
    retrieval_diagnostics: Optional[List[Dict[str, Any]]] # For RAG


# ─────────────────────────────────────────────
# HYBRID RETRIEVER SINGLETON (RAG)
# ─────────────────────────────────────────────

_hybrid_retriever_singleton = None

def get_hybrid_retriever() -> Optional[HybridRetriever]:
    global _hybrid_retriever_singleton
    if _hybrid_retriever_singleton is not None:
        return _hybrid_retriever_singleton

    print("🧩 Initializing Hybrid Retriever...")
    vectorstore_dir = Path(__file__).parent / "vectorstore"
    embeddings = get_embedding_model()

    dense_retriever = None

    pinecone_key = os.environ.get("PINECONE_API_KEY")
    index_name = os.environ.get("PINECONE_INDEX_NAME") or "rag"
    if pinecone_key and index_name:
        try:
            from pinecone import Pinecone as PineconeClient
            from langchain_pinecone import Pinecone
            pc = PineconeClient(api_key=pinecone_key)
            existing_indexes = [idx.name for idx in pc.list_indexes()]
            if index_name in existing_indexes:
                index_obj = pc.Index(index_name)
                vectorstore = Pinecone(index=index_obj, embedding=embeddings)
                dense_retriever = vectorstore.as_retriever(search_kwargs={"k": 30})
        except Exception as e:
            print(f"  ⚠️ Pinecone connection failed ({e})")

    bm25_retriever = None
    chunks_path = vectorstore_dir / "chunks.pkl"
    if chunks_path.exists():
        try:
            with open(chunks_path, "rb") as f:
                chunks = pickle.load(f)
            if chunks:
                from langchain_community.retrievers import BM25Retriever
                bm25_retriever = BM25Retriever.from_documents(chunks)
                bm25_retriever.k = 30
        except Exception as e:
            print(f"  ⚠️ BM25 load failed: {e}")

    if dense_retriever is None and bm25_retriever is None:
        return None

    _hybrid_retriever_singleton = HybridRetriever(
        dense_retriever=dense_retriever,
        bm25_retriever=bm25_retriever,
        fetch_k=40,
        final_k=6,
    )
    return _hybrid_retriever_singleton


# ─────────────────────────────────────────────
# HELPER FUNCTIONS
# ─────────────────────────────────────────────

def get_latest_question(state: AgentState) -> str:
    for msg in reversed(state["messages"]):
        if isinstance(msg, HumanMessage):
            return msg.content
    if len(state["messages"]) > 0:
        return state["messages"][-1].content
    return ""


# ─────────────────────────────────────────────
# 1. ROUTER AGENT
# ─────────────────────────────────────────────

def router_node(state: AgentState):
    question = get_latest_question(state)
    print(f"🚦 Router Agent: Classifying intent for query: '{question}'...")
    
    try:
        llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0, max_tokens=15)
        system_prompt = (
            "You are an expert intent classifier for a smart assistant.\n"
            "Route the user's question to ONE of the following worker agents:\n"
            "- 'rag': For questions about the user's personal info, resume, or uploaded documents.\n"
            "- 'sql': For questions querying structured company data (employees, revenue, salaries, departments).\n"
            "- 'web': For current events, live news, or general web searches.\n"
            "- 'math': For pure mathematical calculations (e.g. 'calculate 5+5').\n"
            "- 'python': For writing or executing python scripts.\n"
            "- 'llm': For general conversational knowledge, chat, and greetings.\n\n"
            "Respond ONLY with the exact single word corresponding to the node: rag, sql, web, math, python, or llm."
        )
        response = llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=question)
        ]).content.strip().lower()

        valid_routes = ["rag", "sql", "web", "math", "python", "llm"]
        route = response if response in valid_routes else "rag"
    except Exception as e:
        print(f"   -> Routing failed ({e}), falling back to 'rag'")
        route = "rag"

    print(f"   -> Routed to: {route}")
    
    # Initialize basic state fields
    return {
        "route": route, 
        "critic_retry_count": 0, 
        "critic_feedback": "", 
        "worker_data": "",
        "draft_response": "",
        "is_approved": False
    }

# ─────────────────────────────────────────────
# 2. WORKER AGENTS
# ─────────────────────────────────────────────

def rag_node(state: AgentState):
    print("📚 RAG Agent: Retrieving from Vector/BM25 stores...")
    question = get_latest_question(state)
    retriever = get_hybrid_retriever()
    
    if retriever is None:
        return {"worker_data": "Knowledge base is empty. No documents uploaded."}

    results = retriever.get_relevant_documents_with_scores(question)
    
    context_chunks = []
    diagnostics = []
    for rank, (doc, meta) in enumerate(results, start=1):
        src = doc.metadata.get("source", "document")
        page = doc.metadata.get("page", 1)
        context_chunks.append(f"[{rank}] (Source: {src}, Page {page}):\n{doc.page_content.strip()}")
        diagnostics.append({
            "citation_id": rank, "source": src, "page": page,
            "snippet": doc.page_content[:150] + "..."
        })

    worker_data = "\n\n".join(context_chunks)
    return {"worker_data": worker_data, "retrieval_diagnostics": diagnostics}

def sql_node(state: AgentState):
    print("🗄️ SQL Agent: Translating query to SQL via Supabase...")
    question = get_latest_question(state)
    
    supabase_url = os.environ.get("SUPABASE_DATABASE_URL")
    if not supabase_url:
        return {"worker_data": "SQL Agent failed: SUPABASE_DATABASE_URL is not set in .env."}
    
    # Langchain's sync SQLDatabase prefers standard postgresql string (psycopg2)
    sync_url = supabase_url.replace("postgresql+asyncpg://", "postgresql://")
    
    try:
        from langchain_community.utilities import SQLDatabase
        db = SQLDatabase.from_uri(sync_url)
        
        # Get dynamic schema from Supabase
        schema = db.get_table_info()
    except Exception as e:
        return {"worker_data": f"Failed to connect to Supabase: {str(e)}"}
    
    llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)
    prompt = (
        f"Given the following Supabase PostgreSQL database schema:\n{schema}\n\n"
        f"Write a valid PostgreSQL query to answer the question: '{question}'. "
        "Return ONLY the raw SQL query, no markdown, no explanation. Do NOT include ```sql."
    )
    
    try:
        sql_query = llm.invoke([HumanMessage(content=prompt)]).content.strip()
        sql_query = sql_query.replace('```sql', '').replace('```', '').strip()
        print(f"   -> Generated SQL: {sql_query}")
        
        # Execute query using LangChain's wrapper
        result = db.run(sql_query)
        
        worker_data = f"Executed Query: {sql_query}\nResults: {result}"
        print("   -> Supabase SQL Query executed successfully.")
    except Exception as e:
        worker_data = f"SQL Execution Failed: {str(e)}"
        
    return {"worker_data": worker_data}

def web_node(state: AgentState):
    print("🌐 Web Agent: Searching the internet...")
    question = get_latest_question(state)
    search = DuckDuckGoSearchRun()
    try:
        result = search.invoke(question)
        worker_data = f"Web Search Results for '{question}':\n{result}"
    except Exception as e:
        worker_data = f"Web search failed: {str(e)}"
    return {"worker_data": worker_data}

def math_node(state: AgentState):
    print("🧮 Math Agent: Computing expression...")
    question = get_latest_question(state)
    llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)
    expr = llm.invoke([HumanMessage(content=f"Extract pure math expression from: '{question}'. Return ONLY expression.")]).content.strip()
    try:
        allowed = set("0123456789+-*/(). ")
        ans = str(eval(expr, {"__builtins__": {}}, {})) if all(c in allowed for c in expr) else "Invalid expression"
        worker_data = f"Math computation of `{expr}` resulted in: {ans}"
    except Exception as e:
        worker_data = f"Math computation failed: {str(e)}"
    return {"worker_data": worker_data}

def python_node(state: AgentState):
    print("🐍 Python Agent: Executing code...")
    question = get_latest_question(state)
    llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)
    code = llm.invoke([HumanMessage(content=f"Write Python code to solve: {question}. Return ONLY executable Python code.")]).content.replace("```python", "").replace("```", "").strip()

    repl = PythonREPLTool()
    try:
        result = repl.invoke(code)
    except Exception as e:
        result = str(e)
    
    worker_data = f"Python Code Executed:\n{code}\n\nOutput:\n{result}"
    return {"worker_data": worker_data}

def llm_node(state: AgentState):
    print("🧠 General LLM Agent: Providing conversational context...")
    # LLM node just provides general knowledge, not much raw data needed.
    return {"worker_data": "Use your general knowledge to answer."}


# ─────────────────────────────────────────────
# 3. PLANNER / SYNTHESIZER AGENT
# ─────────────────────────────────────────────

def planner_node(state: AgentState):
    print("📝 Planner Agent: Drafting comprehensive response...")
    question = get_latest_question(state)
    worker_data = state.get("worker_data", "")
    route = state.get("route", "")
    critic_feedback = state.get("critic_feedback", "")
    
    system_prompt = (
        "You are an expert Synthesis Agent. Your job is to draft a clear, comprehensive, and direct answer to the user's question.\n"
        "You must base your answer strictly on the provided 'Worker Agent Data'.\n"
        "If the route was 'rag', you MUST include inline citations like [1], [2] for factual claims.\n"
        "If the data is insufficient, state that clearly.\n"
    )
    
    if critic_feedback:
        system_prompt += f"\nCRITICAL INSTRUCTION: Your previous draft was rejected by the Critic Agent. You MUST address this feedback: {critic_feedback}\n"

    prompt = f"User Question: {question}\nRoute: {route}\n\nWorker Agent Data:\n{worker_data}"
    
    llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0.2, max_tokens=750)
    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=prompt)
    ])
    
    return {"draft_response": response.content}


# ─────────────────────────────────────────────
# 4. CRITIC / EVALUATOR AGENT
# ─────────────────────────────────────────────

class CriticEvaluation(BaseModel):
    is_approved: bool = Field(description="True if the draft response is accurate, well-formatted, and completely answers the question.")
    feedback: str = Field(description="If not approved, explain exactly what the Planner needs to fix.")

def critic_node(state: AgentState):
    print("🧐 Critic Agent: Evaluating draft response...")
    question = get_latest_question(state)
    draft = state.get("draft_response", "")
    worker_data = state.get("worker_data", "")
    retry_count = state.get("critic_retry_count", 0)
    
    if retry_count >= 2:
        print("   -> Max retries reached, forcing approval to avoid infinite loop.")
        final_msg = AIMessage(content=draft)
        return {"is_approved": True, "messages": [final_msg]}

    llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)
    structured_llm = llm.with_structured_output(CriticEvaluation)
    
    prompt = (
        "You are an expert Critic Agent. Evaluate the Planner's 'Draft Response' against the 'User Question' and 'Worker Data'.\n"
        "Criteria:\n"
        "1. Does the draft fully answer the user's question?\n"
        "2. Is the draft grounded strictly in the worker data without hallucinations?\n"
        "3. If applicable (e.g. RAG), are citations properly formatted?\n\n"
        f"User Question: {question}\n\n"
        f"Worker Data: {worker_data}\n\n"
        f"Draft Response: {draft}"
    )
    
    try:
        evaluation = structured_llm.invoke([HumanMessage(content=prompt)])
        is_approved = evaluation.is_approved
        feedback = evaluation.feedback
    except Exception as e:
        print(f"   -> Critic failed ({e}), defaulting to approved.")
        is_approved = True
        feedback = ""

    if is_approved:
        print("   -> Critic Approved: ✅")
        final_msg = AIMessage(content=draft)
        return {"is_approved": True, "messages": [final_msg]}
    else:
        print(f"   -> Critic Rejected: ❌ Feedback: {feedback}")
        return {"is_approved": False, "critic_feedback": feedback, "critic_retry_count": retry_count + 1}


def critic_router(state: AgentState):
    if state.get("is_approved", True):
        return "end"
    return "planner"


# ─────────────────────────────────────────────
# BUILD LANGGRAPH GRAPH
# ─────────────────────────────────────────────

def build_agent_graph():
    graph = StateGraph(AgentState)

    graph.add_node("router", router_node)
    graph.add_node("rag", rag_node)
    graph.add_node("sql", sql_node)
    graph.add_node("web", web_node)
    graph.add_node("math", math_node)
    graph.add_node("python", python_node)
    graph.add_node("llm", llm_node)
    graph.add_node("planner", planner_node)
    graph.add_node("critic", critic_node)

    graph.add_edge(START, "router")
    
    def route_decision(state: AgentState):
        return state["route"]

    graph.add_conditional_edges(
        "router",
        route_decision,
        {"rag": "rag", "sql": "sql", "web": "web", "math": "math", "python": "python", "llm": "llm"}
    )
    
    # All worker nodes feed into the Planner
    graph.add_edge("rag", "planner")
    graph.add_edge("sql", "planner")
    graph.add_edge("web", "planner")
    graph.add_edge("math", "planner")
    graph.add_edge("python", "planner")
    graph.add_edge("llm", "planner")

    # Planner goes to Critic
    graph.add_edge("planner", "critic")
    
    # Critic conditional routing
    graph.add_conditional_edges(
        "critic",
        critic_router,
        {"end": END, "planner": "planner"}
    )

    return graph.compile()


if __name__ == "__main__":
    app = build_agent_graph()
    print("✅ Multi-Agent Production Graph built successfully.")
