services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neurag_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./vectorstore:/app/vectorstore
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: neurag_frontend
    ports:
      - "5173:80"  # Exposes the React app on port 5173
    depends_on:
      - backend
    restart: unless-stopped
