"""
Integration Test Suite for Production RAG Pipeline with Hybrid Search & Model Flow
"""

import sys
import os
from pathlib import Path

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

from ingest import run_ingestion_pipeline, get_embedding_model
from hybrid_retriever import HybridRetriever, reciprocal_rank_fusion
from citation_verifier import verify_claims_against_sources
from agent import init_retriever, get_hybrid_retriever
from langchain_core.documents import Document

def test_full_pipeline():
    print("=" * 60)
    print("🧪 STARTING PRODUCTION RAG & HYBRID SEARCH PIPELINE TEST")
    print("=" * 60)

    # Step 1: Create test document
    workspace_dir = Path(__file__).parent
    uploads_dir = workspace_dir / "uploads"
    uploads_dir.mkdir(exist_ok=True)
    test_doc = uploads_dir / "test_architecture_spec.txt"

    sample_content = (
        "Project NeuRAG Architecture Document.\n\n"
        "Section 1: Hybrid Search Architecture\n"
        "NeuRAG utilizes a two-stage hybrid retrieval mechanism combining dense semantic embeddings "
        "and sparse BM25 keyword matching. Dense vectors are generated using HuggingFace all-MiniLM-L6-v2 "
        "and indexed into vector databases like ChromaDB, FAISS, or Pinecone. Sparse keyword matching is "
        "handled via Rank-BM25 over pre-processed text chunks.\n\n"
        "Section 2: Reciprocal Rank Fusion (RRF) & Reranking\n"
        "Retrieved documents from dense and sparse algorithms are merged using Reciprocal Rank Fusion (RRF) "
        "with a smoothing parameter k=60. Top candidates are then re-ranked using ms-marco-MiniLM-L-6-v2 "
        "Cross-Encoder to maximize contextual precision before feeding context into the LLM system prompt.\n\n"
        "Section 3: Citation Grounding & Verification\n"
        "Answers generated by Groq llama-3.1-8b-instant contain mandatory inline citations [1], [2]. "
        "The automated citation verifier measures sentence-level n-gram overlap and semantic score "
        "to ensure 100% answer faithfulness against retrieved source snippets."
    )

    with open(test_doc, "w", encoding="utf-8") as f:
        f.write(sample_content)

    print(f"📄 Created test document at: {test_doc}")

    # Step 2: Test Ingestion Pipeline
    print("\n--- STAGE 1: Document Ingestion & Chunking ---")
    vectorstore_dir = workspace_dir / "vectorstore"
    ingest_result = run_ingestion_pipeline(test_doc, vectorstore_dir)
    print(f"✅ Ingestion successful! Chunks added: {ingest_result['chunks_added']}, Total: {ingest_result['total_chunks']}")

    # Step 3: Test Hybrid Retriever Singleton
    print("\n--- STAGE 2: Hybrid Search (Dense + BM25 + RRF + CrossEncoder) ---")
    retriever = init_retriever()
    assert retriever is not None, "HybridRetriever initialization failed!"

    test_query = "How does NeuRAG perform hybrid search and reranking?"
    print(f"🔍 Executing Query: '{test_query}'")

    results = retriever.get_relevant_documents_with_scores(test_query)
    print(f"✅ Retrieved {len(results)} top candidate documents:")

    for doc, meta in results:
        print(f"   • [Citation #{meta.get('final_rank')}] Source: {doc.metadata.get('source')} (Page {doc.metadata.get('page', 1)})")
        print(f"     - Dense Rank: {meta.get('dense_rank')} | BM25 Rank: {meta.get('bm25_rank')}")
        print(f"     - RRF Score: {meta.get('rrf_score')} | Cross-Encoder Score: {meta.get('cross_encoder_score')}")
        print(f"     - Snippet: {doc.page_content[:120].strip()}...\n")

    assert len(results) > 0, "No documents retrieved!"

    # Step 4: Test Citation Verification
    print("\n--- STAGE 3: Grounded Answer & Citation Verification ---")
    generated_answer = (
        "NeuRAG utilizes a two-stage hybrid retrieval mechanism combining dense semantic embeddings "
        "and sparse BM25 keyword matching [1]. Candidates are merged using Reciprocal Rank Fusion (RRF) "
        "and re-ranked with the ms-marco-MiniLM-L-6-v2 Cross-Encoder model [2]."
    )

    retrieved_docs = [doc for doc, _ in results]
    citations, score = verify_claims_against_sources(generated_answer, retrieved_docs)

    print(f"✅ Citation Groundedness Score: {score * 100:.1f}%")
    for c in citations:
        print(f"   • Citation [{c['citation_id']}] Grounded={c['grounded']} | Score={c['confidence_score']}")
        print(f"     Claim: '{c['claim']}'")

    assert score >= 0.5, "Groundedness verification score too low!"

    print("\n" + "=" * 60)
    print("🎉 ALL PRODUCTION RAG & HYBRID SEARCH TESTS PASSED SUCCESSFULLY!")
    print("=" * 60)

if __name__ == "__main__":
    test_full_pipeline()
